/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import javax.swing.JOptionPane;
import Controller.MagStripeCard;
import Model.CreditCardInfo;
/**
 *
 * @author Javier_Alay
 */
public class MagneticCardReader extends javax.swing.JFrame {
    private CreditCardInfo infoCard;
    private boolean isReaded;
    private javax.swing.JTextField name;
    private javax.swing.JTextField number;
    private javax.swing.JTextField expiration;
    /**
     * Creates new form magneticCardReader
     * @param name
     * @param number
     * @param expiration
     */
    public MagneticCardReader(javax.swing.JTextField name, javax.swing.JTextField number, javax.swing.JTextField expiration) {
        this.setUndecorated(true);
        initComponents();
        this.isReaded = false;
        this.name = name;
        this.number = number;
        this.expiration = expiration;
    }
    public MagneticCardReader(){
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        in = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Deslice la tarjeta magnética:");

        in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/magneticCard.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(in, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public CreditCardInfo readMagneticCard(){
        CreditCardInfo cardInfo = null;
        try{
            MagStripeCard msc = new MagStripeCard(in.getText());
            String name = msc.getLastName()+" "+msc.getFirstName();
            String cardNumber = msc.getAccountNumber();
            int expirationMonth = Integer.parseInt(msc.getExpirationMonth());
            int expirationYear = Integer.parseInt(msc.getExpirationYear());
            String cardType = Controller.CreditCardInfo.cardType(msc.getAccountNumber().toString());
            boolean isValid = Controller.CreditCardInfo.validateChecksum(msc.getAccountNumber().toString());
            
            cardInfo = new CreditCardInfo(name,cardNumber,expirationMonth,expirationYear,false);
            
        }catch(Exception e){
            System.out.println(e);
            if(e.toString().equals("Controller.MagstripeParseException: Missing delimiter [/] in account holder name data")){
                JOptionPane.showMessageDialog(null,"Tarjeta de Chip","",2);
            }
            
        }
    return cardInfo;
    }
    
    public boolean isReaded(){
        return isReaded;
    }
    
    private void putData(CreditCardInfo info){
        name.setText(info.getNombreTarjeta().replace("  ", ""));
        
        String cardNumber = String.valueOf(info.getNumeroTarjeta());
        number.setText(cardNumber.substring(0,4)+"-"+cardNumber.substring(4,8)+"-"+cardNumber.substring(8,12)+"-"+cardNumber.substring(12,16));
        
        
        expiration.setText(String.valueOf(info.getMesFin())+"/"+String.valueOf(info.getAnioFin()));
        
        
}
    private void inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inActionPerformed
        // TODO add your handling code here:
        CreditCardInfo ccr = readMagneticCard();
        if(ccr!=null)
            putData(ccr);
        isReaded = true;
        this.dispose();
    }//GEN-LAST:event_inActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MagneticCardReader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MagneticCardReader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MagneticCardReader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MagneticCardReader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MagneticCardReader().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField in;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
